apiVersion: v1
kind: Service
metadata:
  name: kiwi-tcms
  namespace: atp-tcms
  labels:
    app.kubernetes.io/name: kiwi-tcms
    app.kubernetes.io/part-of: atp-tcms
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kiwi-tcms
  ports:
    - name: https
      port: 8443
      targetPort: https

