apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atp-tcms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hklier/atp-tcms.git
    targetRevision: main
    path: deploy/kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: atp-tcms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

